### ISSUE TITLE
StatefulWidget, widget test, autofocus, cause A TextEditingController was used after being disposed

### ISSUE THREAD

**Issue by bradyt** [AbdulRahmanAlHamali/flutter_typeahead#155]
If I clone your project, and modify contents of `test/flutter_typeahead_test.dart` to be the following,

<details>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';

void main() {
  testWidgets('Test.', (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: DescriptionField(),
        ),
      ),
    );

    await tester.pumpAndSettle();
  });
}

class DescriptionField extends StatefulWidget {
  const DescriptionField();

  @override
  DescriptionFieldState createState() => DescriptionFieldState();
}

class DescriptionFieldState extends State<DescriptionField> {
  TextEditingController controller = TextEditingController();

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return TypeAheadField<String>(
      textFieldConfiguration: TextFieldConfiguration<dynamic>(
        controller: controller,
        autofocus: true,
      ),
      suggestionsCallback: (_) => [],
      itemBuilder: (_, __) => Container(),
      onSuggestionSelected: (_) {},
    );
  }
}
```

</details>

Then I get the following error:

```
$ flutter test
00:04 +0: Test.                                                                                                                                           
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
A TextEditingController was used after being disposed.
Once you have called dispose() on a TextEditingController, it can no longer be used.
```

<details>

```
When the exception was thrown, this was the stack:
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:105:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:111:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:166:12)
#3      _SuggestionsListState.dispose (package:flutter_typeahead/flutter_typeahead.dart:1087:24)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4700:12)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#7      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#22     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5839:16)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#31     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#37     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
#38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
#41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#63     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#65     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#66     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#67     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#68     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#69     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#71     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#72     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#73     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#74     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#75     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#76     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
#77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#79     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#80     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#81     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#82     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#83     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#84     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#86     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#87     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#88     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#89     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#90     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#91     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#92     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#93     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#94     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
#95     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#96     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#97     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#98     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#99     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#100    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#101    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#102    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#103    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#104    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#105    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#106    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#107    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#108    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#109    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#110    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#111    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#113    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#114    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#115    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#116    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#117    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#118    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#119    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#120    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#121    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#122    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#123    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#124    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
#125    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#126    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#127    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#128    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#129    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#130    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#131    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#132    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#133    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#134    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#135    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#136    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#137    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#138    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#139    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#140    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#141    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#142    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
#143    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#144    ListIterable.forEach (dart:_internal/iterable.dart:41:13)
#145    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1931:25)
#146    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2698:27)
#147    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2529:15)
#148    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2697:7)
#149    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1029:18)
#150    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#151    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1108:15)
#152    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1047:9)
#153    AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:957:5)
#154    runApp (package:flutter/src/widgets/binding.dart:983:7)
#155    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:713:7)
#167    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#180    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1102:17)
#182    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1090:35)
(elided 39 frames from class _FakeAsync, dart:async, dart:async-patch, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:04 +0 -1: Test. [E]                                                                                                                                    
  Test failed. See exception logs above.
  The test description was: Test.
  
00:04 +0 -1: Some tests failed.
```

</details>

**Comment by dnfield** [comment]
Does this still throw?

```dart
class DescriptionFieldState extends State<DescriptionField> {
  TextEditingController controller = TextEditingController();
  TextFieldConfiguration<dynamic> textFieldConfiguration;

  @override
  void initState() {
    super.initState();
    textFieldConfiguration = TextFieldConfiguration<dynamic>(
      controller: controller,
      autofocus: true,
    );
  }

  @override
  void dispose() {
    textFieldConfiguration.controller = null;
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return TypeAheadField<String>(
      textFieldConfiguration: textFieldConfiguration,
      suggestionsCallback: (_) => [],
      itemBuilder: (_, __) => Container(),
      onSuggestionSelected: (_) {},
    );
  }
}
```

**Comment by dnfield** [comment]
Assuming that works, TextFieldConfiguration should probably have a a dispose method on it

**Comment by bradyt** [comment]
> Does this still throw?
> [...]

@dnfield Unfortunately yes, with

```
$ flutter test
00:02 +0: loading /Users/alice/code/flutter_typeahead/test/flutter_typeahead_test.dart                                                                
Compiler message:
flutter_typeahead_test.dart:39:28: Error: The setter 'controller' isn't defined for the class 'TextFieldConfiguration<dynamic>'.
 - 'TextFieldConfiguration' is from 'package:flutter_typeahead/flutter_typeahead.dart' ('../lib/flutter_typeahead.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'controller'.
    textFieldConfiguration.controller = null;
                           ^^^^^^^^^^
00:02 +0 -1: loading /Users/alice/code/flutter_typeahead/test/flutter_typeahead_test.dart [E]                                                         
  Failed to load "/Users/alice/code/flutter_typeahead/test/flutter_typeahead_test.dart":
  Compilation failed
  Test: /Users/alice/code/flutter_typeahead/test/flutter_typeahead_test.dart
  Shell: /Users/alice/opt/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester
  
  
00:02 +0 -1: Some tests failed.
```

**Comment by sterlp** [comment]
Would removing line 1102 fix the issue? As this seems to be the "change" to the controller which produces the problem.

![image](https://user-images.githubusercontent.com/774984/88801281-bb48a580-d1a9-11ea-8343-964dc0faaf7d.png)

The controller field is final -- means it can't be changed anymore later on
![image](https://user-images.githubusercontent.com/774984/88801394-edf29e00-d1a9-11ea-986c-c7f878adc276.png)

**Comment by sterlp** [comment]
Created pull request for the issue https://github.com/AbdulRahmanAlHamali/flutter_typeahead/pull/223

**Comment by sjmcdowall** [comment]
Fixed with PR
