### ISSUE TITLE
Getting error : line 1687 pos 12: 'hasSize': RenderBox was not laid out: RenderLeaderLayer

### ISSUE THREAD

**Issue by nateshmbhat** [AbdulRahmanAlHamali/flutter_typeahead#160]
```
2020-02-28 14:45:01.605 3252-3323/com.example.samplesdkapp E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1687 pos 12: 'hasSize': RenderBox was not laid out: RenderLeaderLayer#13fec NEEDS-LAYOUT NEEDS-PAINT
    #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
    #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
    #2      RenderBox.size (package:flutter/src/rendering/box.dart:1687:12)
    #3      _SuggestionsBox._adjustMaxHeightAndOrientation (package:flutter_typeahead/flutter_typeahead.dart:1639:24)
    #4      _SuggestionsBox.resize (package:flutter_typeahead/flutter_typeahead.dart:1628:7)
    #5      _SuggestionsBox.onChangeMetrics (package:flutter_typeahead/flutter_typeahead.dart:1743:7)
    <asynchronous suspension>
    #6      _TypeAheadFieldState.didChangeMetrics (package:flutter_typeahead/flutter_typeahead.dart:736:26)
    #7      WidgetsBinding.handleMetricsChanged (package:flutter/src/widgets/binding.dart:428:16)
    #8      _rootRun (dart:async/zone.dart:1126:13)
    #9      _CustomZone.run (dart:async/zone.dart:1023:19)
    #10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #11     _invoke (dart:ui/hooks.dart:259:10)
    #12     _updateWindowMetrics (dart:ui/hooks.dart:63:3)

```

**Comment by pureimpro** [comment]
Hi, any update ? 
I have the same issue.
There may be a link with route navigation because i noticed in my app that navigator.pushNamed call to a page including type_ahead field leads to this error message, whereas standard widget call in a page works fine.
Any help is much appreciated !

**Comment by wwwdata** [comment]
I looked at the problem now and opened a PR. Could you please try this out if it fixes the problems for you? I think the problem was that if the TypeAheadField was rendered for example on a Screen that was covered by another Screen in a NavigationStack, then it was still trying to find its RenderBox, which would then not exist. So I added a null and hasSize check in there that it doesn't fail and throws exceptions.
