### ISSUE TITLE
Debounce timer not cancelled on dispose

### ISSUE THREAD

**Issue by llucie** [AbdulRahmanAlHamali/flutter_typeahead#213]
In `_SuggestionsListState` class, a Timer is instantiated and launched in `initState`:

```dart
this._debounceTimer = Timer(widget.debounceDuration, () async {
  if (this._debounceTimer.isActive) return;
    if (_isLoading) {
      _isQueued = true;
      return;
    }

    await this._getSuggestions();
    while (_isQueued) {
      _isQueued = false;
      await this._getSuggestions();
    }
});
```

But this Timer is not cancelled upon dispose.

This causes an exception while running Widget tests on an App containing a `TypeAheadField` or a `TypeAheadFormField`.

```
Pending timers:
Timer (duration: 0:00:00.300000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:283:41)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:247:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:180:19)
#5      _SuggestionsListState.initState.<anonymous closure> (package:flutter_typeahead/flutter_typeahead.dart:1033:29)
#6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:207:21)
#7      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:274:5)
#8      TextEditingController.text= (package:flutter/src/widgets/editable_text.dart:148:5)
#9      _CityTextFieldState.build.<anonymous closure>.<anonymous closure> (package:geolocatorapp/cityTextField.dart:40:65)
(elided 42 frames from dart:async, dart:async-patch, and package:stack_trace)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1168 pos 12: '!timersPending'
```

Add this line in `dispose()` method of `_SuggestionsListState` to get rid of the error:

```dart
_debounceTimer?.cancel();
```

**Comment by sjmcdowall** [comment]
Can you see if the latest bug fixes fixed this

**Comment by awhitford** [comment]
From just looking at the code, I think `_debounceTimer?.cancel();` still needs to be added to the `dispose()` method, otherwise there is a risk that the widget is disposed while the debounce timer is running.

**Comment by wwwdata** [comment]
also stumbled upon this problem now when I wanted to make a widget test. Can we quickly fix this? I could also open a PR for this.

**Comment by sjmcdowall** [comment]
@wwwdata -- if you write a PR that includes a test I'll merge it.

**Comment by wwwdata** [comment]
ok, opened my small PR with a test.
